### ISSUE TITLE
代码无法打开

### ISSUE THREAD

**Issue by dosemeion** [yangyahu-1994/VAMYOLOX#1]
你好，我想了解一下TAM的结构，但是代码无法打开

**Comment by yahuyang** [comment]
你好，感谢关注。
代码中应该有TAM的结构。
关于TAM的结构，你也可以查看这个[链接](https://blog.csdn.net/weixin_41790863/article/details/123983337?spm=1001.2014.3001.5501)，有对应的解释以及代码实现。

**Comment by dosemeion** [comment]
> 你好，感谢关注。 代码中应该有TAM的结构。 关于TAM的结构，你也可以查看这个[链接](https://blog.csdn.net/weixin_41790863/article/details/123983337?spm=1001.2014.3001.5501)，有对应的解释以及代码实现。

好的，谢谢
